# Commit: db4678a https://github.com/dockstore/dockstore-deploy/commits/db4678a
# Template for creating ES log groups (only one created for now)
# After deploying this stack but before creating ES, you need to add a resource policy for the Elasticsearch service
# to have access. Lame that it is not supported by CloudFormation!
#

Description: >
  Manages the Elasticsearch service log group(s)

Parameters:
  LogGroupName:
    Description: The name of the log group, which equals the domain
    Type: String
    Default: /aws/aes/domains/dev-dockstore-elasticsearch/application-logs

  # Tags for allocated resources
  ServiceArea:
    Description: Which service area resource is related to?
    Type: String
  Proj:
    Description: Unity Project
    Type: String
  Venue:
    Description: Venue that the resource is being deployed on.
    Type: String
  Component:
    Description: Unity component
    Type: String
  CreatedBy:
    Description: Same as ServiceArea
    Type: String
  Env:
    Description: Same as Venue
    Type: String
  Stack:
    Description: Same as Component
    Type: String

Resources:
  EsApplicationLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Ref LogGroupName
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}-es-log-group'
        - Key: ServiceArea
          Value: !Ref ServiceArea
        - Key: Proj
          Value: !Ref Proj
        - Key: Venue
          Value: !Ref Venue
        - Key: Component
          Value: !Ref Component
        - Key: CreatedBy
          Value: !Ref CreatedBy
        - Key: Env
          Value: !Ref Env
        - Key: Stack
          Value: !Ref Stack

Outputs:
  EsApplicationLogGroup:
    Description: The ES application logs group
    Value: !GetAtt 'EsApplicationLogGroup.Arn'
    Export:
      Name: !Sub '${AWS::StackName}-EsApplicationLogGroup'


