# This file can update the JupyterHub Helm chart's default configuration values.
#
# For reference see the configuration reference and default values, but make
# sure to refer to the Helm chart version of interest to you!
#
# Introduction to YAML:     https://www.youtube.com/watch?v=cdLNKUoMc6c
# Chart config reference:   https://zero-to-jupyterhub.readthedocs.io/en/stable/resources/reference.html
# Chart default values:     https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/HEAD/jupyterhub/values.yaml
# Available chart versions: https://jupyterhub.github.io/helm-chart/

singleuser:
  defaultUrl: "/lab"
  extraEnv:
    JUPYTERHUB_SINGLEUSER_APP: "jupyter_server.serverapp.ServerApp"
  # Defines the default image
  image:
    name: jupyter/base-notebook
    tag: latest
  profileList:
    - display_name: "Jupyter - Minimal environment"
      description: "To avoid too much bells and whistles: Python."
      default: true
    - display_name: "Jupyter - Datascience environment"
      description: "If you want the additional bells and whistles: Python, R, and Julia."
      kubespawner_override:
        image: jupyter/datascience-notebook:latest
    - display_name: "Jupyter - Spark environment"
      description: "The Jupyter Stacks spark image!"
      kubespawner_override:
        image: jupyter/all-spark-notebook:latest
    - display_name: "Unity - Datascience Environment"
      description: "Extends Jupyter datascience environment to include the Dockstore client and AWS client"
      kubespawner_override:
        image: public.ecr.aws/unity-ads/datascience:r0.1.0
    - display_name: "Unity - Sounder SIPS Development Environment"
      description: "Packages and tools replicating the JPL Sounder SIPS development environment"
      kubespawner_override:
        image: public.ecr.aws/unity-ads/sounder_sips_dev:r0.1.0
  storage:
    extraVolumes:
      - name: ${shared_volume_name}
        persistentVolumeClaim:
          claimName: ${shared_volume_name}
    extraVolumeMounts:
      - name: ${shared_volume_name}
        mountPath: /unity/ads
  extraAnnotations:
    iam.amazonaws.com/role: ${kube2iam_role_arn}
  cloudMetadata:
    blockWithIptables: false
    ip: 169.254.169.254
hub:
  baseUrl: ${jupyter_base_path}
  config:
    OAuthenticator:
      oauth_callback_url: ${jupyter_base_url}/hub/oauth_callback
      client_id: ${oauth_client_id}
      client_secret: ${oauth_client_secret}
    GenericOAuthenticator:
      login_service: "Unity Common Services"
      username_key: username
      authorize_url: ${cognito_base_url}/oauth2/authorize
      token_url: ${cognito_base_url}/oauth2/token
      userdata_url: ${cognito_base_url}/oauth2/userInfo
    JupyterHub:
      authenticator_class: generic-oauth
proxy:
  service:
    type: NodePort
    nodePorts: 
      http: ${jupyter_proxy_port}
